apiVersion: apps/v1
kind: Deployment
metadata:
  name:  swiggy
  namespace: default
  labels:
    app:  swiggy
spec:
  selector:
    matchLabels:
      app: swiggy
  replicas: 1
  template:
    metadata:
      labels:
        app:  swiggy
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  swiggy
        image:  docker.io/anikesh372/swiggy:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  3000
          name:  swiggy